### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by luqin** [passy/autoprefixer-loader#23]
"autoprefixer-loader": "^2.0.0"

```
TypeError: undefined is not a function
    at Object.<anonymous> (/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/lib/autoprefixer.js:19:28)
    at Object.<anonymous> (/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/lib/autoprefixer.js:88:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_modules/autoprefixer-loader/index.js:2:24)
    at Module._compile (module.js:460:26)
```

**Comment by ai** [comment]
@luqin try [postcss-loader](https://github.com/postcss/postcss-loader) with `autoprefixer` plugin.

**Comment by luqin** [comment]
@ai OK
